version: '3'

tasks:
  init:
    cmds:
      - terragrunt run-all init

  plan:
    cmds:
      - terragrunt run-all plan

  get-gke-credentials:
    internal: true
    cmds:
      - |
        cd terraform/gke && \
        CLUSTER_NAME=$(terragrunt output -raw cluster_name) && \
        LOCATION=$(terragrunt output -raw cluster_location) && \
        gcloud container clusters get-credentials $CLUSTER_NAME --region $LOCATION
      - kubectl get cluster-info

  k8s-apply:
    cmds:
      - helmfile --file ./k8s/helmfile.yaml template | kubectl apply -f -

  k8s-delete:
    cmds:
      - helmfile --file ./k8s/helmfile.yaml template | kubectl delete -f -

  tf-apply:
    cmds:
      - terragrunt run-all apply

  tf-destroy:
    cmds:
      - terragrunt run-all destroy

  apply:
    cmds:
      - task: tf-apply
      - task: get-gke-credentials
      - task: k8s-apply

  destroy:
    cmds:
      - task: k8s-delete
      - task: tf-destroy
