version: '3'

tasks:
  init:
    cmds:
      - terragrunt run-all init

  plan:
    cmds:
      - terragrunt run-all plan

  apply:
    cmds:
      - terragrunt run-all apply
      - helmfile --file ./k8s/helmfile.yaml | kubectl apply -f -

  destroy:
    cmds:
      - terragrunt run-all destroy
      - helmfile --file ./k8s/helmfile.yaml | kubectl delete -f -
