apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secret-manager
  target:
    name: argocd-github-oauth
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: argocd-github-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: argocd-github-oauth-client-secret
