helmfiles:
  - path: ./common/helmfile.yaml
    selectors:
      - name=common

  - path: ./external-dns/helmfile.yaml
    selectors:
      - name=external-dns
      - name=extra

  - path: ./external-secrets/helmfile.yaml
    selectors:
      - name=external-secrets
      - name=extra

  - path: ./gateway-api/helmfile.yaml
    selectors:
      - name=gateway-api

  - path: ./sample/helmfile.yaml
    selectors:
      - name=external-dns
      - name=external-secrets

environments:
  default:
    values:
      - ../env.yaml
