apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-external-secrets-example
  namespace: sample
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: external-secrets-example
    creationPolicy: Owner
  data:
    - secretKey: external-secrets-example
      remoteRef:
        key: external-secrets-example
        version: latest
