repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.13.1
    values:
      - values.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
