# https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
provider: google
google:
  project: daylight-labo

domainFilters:
  - labo.daylight55.com
txtOwnerId: daylight-labo-cluster
registry: txt
policy: sync

sources:
  - gateway-httproute

interval: '1m'
logLevel: debug

serviceAccount:
  create: true
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@daylight-labo.iam.gserviceaccount.com

rbac:
  create: true

extraArgs:
  - --google-zone-visibility=public
