provider: google
google:
  project: daylight-labo
  serviceAccountSecret: external-dns-sa

domainFilters:
  - labo.daylight55.com
txtOwnerId: daylight-labo-cluster
registry: txt
policy: sync
source:
  - gateway-httproute
  - gateway-tlsroute

interval: '1m'

serviceAccount:
  create: true
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@daylight-labo.iam.gserviceaccount.com

rbac:
  create: true

extraArgs:
  - --google-zone-visibility=public
