apiVersion: v1
kind: Namespace
metadata:
  name: sample
  labels:
    name: sample
  annotations:
    description: 'Namespace for sample resources'
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
  annotations:
    description: 'Namespace for External Secrets Operator'
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
  annotations:
    description: 'Namespace for External DNS Operator'
