apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: daylight-labo
      auth:
        workloadIdentity:
          # GKEクラスターのWorkload Identity Pool
          clusterLocation: us-west1-c
          clusterName: daylight-labo-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
